# Generated by Django 3.2.3 on 2021-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('alt', models.CharField(blank=True, max_length=240, null=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
            ],
        ),
    ]
